# Generated by Django 3.2.4 on 2021-06-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_productcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vendor', models.CharField(max_length=50)),
                ('name_of_shop', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('phone_number1', models.CharField(max_length=15)),
                ('email_add', models.EmailField(max_length=250, unique=True)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='commerce.ProductCategory')),
            ],
        ),
    ]
