# Generated by Django 3.2.4 on 2021-06-28 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Cart',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=100)),
                ('id_example', models.ImageField(blank=True, upload_to='id_examples')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_short_name', models.CharField(blank=True, help_text='A short name eg.Iphone SE', max_length=100)),
                ('product_brand', models.CharField(help_text='a brand name eg. Apple', max_length=250)),
                ('product_description', models.TextField(blank=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_image_1', models.ImageField(blank=True, upload_to='products')),
                ('product_image_2', models.ImageField(blank=True, upload_to='products')),
                ('product_image_3', models.ImageField(blank=True, upload_to='products')),
                ('product_image_4', models.ImageField(blank=True, upload_to='products')),
                ('product_image_5', models.ImageField(blank=True, upload_to='products')),
                ('product_video', models.FileField(blank=True, upload_to='videos/')),
                ('product_stock', models.IntegerField()),
                ('operating_system', models.CharField(blank=True, max_length=25)),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='VendorSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vendor', models.CharField(max_length=50)),
                ('name_of_shop', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('phone_number1', models.CharField(blank=True, max_length=15)),
                ('biz_registration', models.ImageField(blank=True, upload_to='Vendor_biz_registration')),
                ('shop_place_image', models.ImageField(blank=True, upload_to='Vendor_shops')),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('id_image', models.ImageField(upload_to='ids_of_vendor')),
                ('current_image', models.ImageField(blank=True, help_text='current image please', upload_to='vendors_image')),
                ('email_add', models.EmailField(max_length=250, unique=True)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='commerce.ProductCategory')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.ids')),
            ],
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.vendorsign'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.product'),
        ),
    ]
