# Generated by Django 3.2.4 on 2021-06-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_auto_20210627_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_short_name', models.CharField(blank=True, help_text='A short name eg.Iphone SE', max_length=100)),
                ('product_brand', models.CharField(help_text='a brand name eg. Apple', max_length=250)),
                ('product_description', models.TextField(blank=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_image_1', models.ImageField(blank=True, upload_to='products')),
                ('product_image_2', models.ImageField(blank=True, upload_to='products')),
                ('product_image_3', models.ImageField(blank=True, upload_to='products')),
                ('product_image_4', models.ImageField(blank=True, upload_to='products')),
                ('product_image_5', models.ImageField(blank=True, upload_to='products')),
                ('product_video', models.FileField(blank=True, upload_to='videos/')),
                ('product_stock', models.IntegerField()),
                ('operating_system', models.CharField(blank=True, max_length=25)),
                ('available', models.BooleanField(default=True)),
                ('vendor', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
